Repository stepanzubkov/florgon-gatey-plasmoid, pull requests merged in 2023-06, with the labels that each got.

#18 Rewrite config on QQC2
  plasmoid/contents/ui/config/ConfigComboBox.qml
  plasmoid/contents/ui/config/ConfigForDevelopers.qml
  plasmoid/contents/ui/config/ConfigGeneral.qml
  plasmoid/contents/ui/config/StatusLabel.qml
Labels: enhancement, invalid

#16 Version 2.0.0: New domain
  LICENSE
  README.md
  build.sh
  build_and_restart.sh
  plasmoid/contents/config/config.qml
  plasmoid/contents/config/main.xml
  plasmoid/contents/locale/nl/LC_MESSAGES/plasma_applet_com.florgon.gatey.mo
  plasmoid/contents/locale/ru/LC_MESSAGES/plasma_applet_com.florgon.gatey.mo
  plasmoid/contents/ui/FullRepresentation.qml
  plasmoid/contents/ui/config/ConfigComboBox.qml
  plasmoid/contents/ui/config/ConfigForDevelopers.qml
  plasmoid/contents/ui/config/ConfigGeneral.qml
  plasmoid/contents/ui/config/StatusLabel.qml
  plasmoid/contents/ui/config/oauth.js
  plasmoid/contents/ui/config/projects.js
  plasmoid/contents/ui/config/translated_errors.js
  plasmoid/contents/ui/events.js
  plasmoid/contents/ui/main.qml
  plasmoid/contents/ui/urlUtils.js
  plasmoid/metadata.desktop
  plasmoid/translate/ReadMe.md
  plasmoid/translate/nl.po
  plasmoid/translate/ru.po
  plasmoid/translate/template.pot
Labels: enhancement

#19 Updated Dutch translation
  plasmoid/translate/ReadMe.md
  plasmoid/translate/nl.po
Labels: enhancement

#20 Version v2.1.0: Dutch translations updated
  README.md
  plasmoid/metadata.desktop
  plasmoid/translate/ReadMe.md
  plasmoid/translate/nl.po
Labels: enhancement

#21 Patch v2.1.1
  plasmoid/contents/locale/nl/LC_MESSAGES/plasma_applet_com.florgon.gatey.mo
  plasmoid/contents/locale/ru/LC_MESSAGES/plasma_applet_com.florgon.gatey.mo
  plasmoid/contents/ui/config/translated_errors.js
  plasmoid/metadata.desktop
  plasmoid/translate/ReadMe.md
  plasmoid/translate/nl.po
  plasmoid/translate/ru.po
  plasmoid/translate/template.pot
Labels: bug, enhancement
